-- Generated SQL inserts for ruta table
TRUNCATE TABLE ruta CASCADE;
ALTER SEQUENCE ruta_ruta_id_seq RESTART WITH 1;
INSERT INTO ruta (nombre, tipo_corrida, terminal_salida_id, terminal_llegada_id) VALUES
('México TAPO - Veracruz', 'local', 23, 94),
('Ejecutiva del sur - Veracruz', 'local', 21, 94),
('México TAPO Lujo - Veracruz', 'de paso', 23, 94),
('Central México Norte - Veracruz', 'de paso', 20, 94),
('Terrapuerto el Ángel - Veracruz', 'local', 27, 94),
('México TAPO Lujo - Veracruz', 'local', 23, 94),
('México TAPO - Veracruz', 'de paso', 23, 94),
('Ejecutiva del sur - Veracruz', 'Viaje local', 21, 94),
('México TAPO Lujo - Veracruz', 'Viaje de paso', 23, 94),
('Santa Martha Acatitla - Veracruz', 'Viaje de paso', 26, 94),
('México TAPO - Veracruz', 'Viaje de paso', 23, 94),
('Central México Norte - Veracruz', 'local', 20, 94),
('Central México Norte - Veracruz', 'Viaje local', 20, 94),
('Central México Norte - Veracruz', 'Viaje de paso', 20, 94),
('Orizaba - Puebla CAPU', 'Viaje de paso', 88, 56),
('Orizaba - Puebla CAPU', 'de paso', 88, 56),
('Tampico - Veracruz', 'local', 76, 94),
('Tampico - Veracruz', 'Viaje de paso', 76, 94),
('Xalapa CAXA - Minatitlán', 'local', 97, 86),
('Ciudad del Carmen - Villahermosa', 'local', 4, 71),
('Ciudad del Carmen - Villahermosa', 'Viaje de paso', 4, 71),
('Ciudad del Carmen - Villahermosa', 'Viaje local', 4, 71),
('Ciudad del Carmen - Villahermosa', 'de paso', 4, 71),
('México TAPO - Tehuacán', 'local', 23, 58),
('México TAPO - Tehuacán', 'de paso', 23, 58),
('México TAPO - Tehuacán', 'Viaje de paso', 23, 58),
('Chetumal - Playa del Carmen alterna', 'local', 65, 67),
('Chetumal - Cancún', 'local', 65, 62),
('Chetumal - Aeropuerto Cancún T2', 'local', 65, 62),
('Cosamaloapan - Veracruz', 'de paso', 83, 94),
('Cosamaloapan - Veracruz', 'Viaje de paso', 83, 94),
('Minatitlán - Veracruz', 'de paso', 86, 94),
('Minatitlán - Veracruz', 'Viaje de paso', 86, 94),
('Coatzacoalcos - Mérida Centro Histórico', 'de paso', 80, 99),
('Coatzacoalcos - Mérida Centro Histórico', 'Viaje de paso', 80, 99),
('Coatzacoalcos - Mérida Centro Histórico', 'local', 80, 99),
('Coatzacoalcos - Veracruz', 'Viaje de paso', 80, 94),
('Coatzacoalcos - Veracruz', 'local', 80, 94),
('Coatzacoalcos - Veracruz', 'de paso', 80, 94),
('Coatzacoalcos - Xalapa CAXA', 'local', 80, 97),
('México TAPO - Villahermosa', 'local', 23, 71),
('México TAPO - Villahermosa', 'de paso', 23, 71),
('México TAPO - Villahermosa', 'Viaje de paso', 23, 71),
('Coatzacoalcos - México TAPO', 'Viaje local', 80, 23),
('Coatzacoalcos - México TAPO', 'local', 80, 23),
('Coatzacoalcos - México TAPO Lujo', 'local', 80, 23),
('Coatzacoalcos - México TAPO', 'de paso', 80, 23),
('Coatzacoalcos - México TAPO Lujo', 'Viaje local', 80, 23),
('Coatzacoalcos - México TAPO Lujo', 'de paso', 80, 23),
('Orizaba - Veracruz', 'local', 88, 94),
('Orizaba - Veracruz', 'de paso', 88, 94),
('Orizaba - Aeropuerto Veracruz', 'local', 88, 94),
('Orizaba - Veracruz norte', 'local', 88, 96),
('Orizaba - Veracruz', 'Viaje local', 88, 94);
